services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/restoration_erp?schema=public
    depends_on:
      - db
